server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: notification-service
  mail:
    username:
    password:
    host: smtp.gmail.com
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          starttls:
            enabled: true
          auth: true
          ssl:
            trust: smtp.gmail.com
  cloud:
    stream:
      default-binder: kafka
      bindings:
        eventConsumer-in-0:
          destination: notification-events
      kafka:
        binder:
          brokers:
            - localhost:9092